import { bodyParam, folderLocator, libraryLocator, pathLocator, queryParam } from '../catalogue/common-params';
import type { ResourceSpec } from '../catalogue/types';
import { deleteWithTrash } from './delete-with-trash';

export const folder: ResourceSpec = {
	value: 'folder',
	name: 'Folder',
	description: 'Organizes files inside a library',
	operations: [
		{
			resource: 'folder',
			operation: 'getAll',
			name: 'Get Many',
			action: 'Get many folders',
			description: 'List folders in a library or under a parent folder',
			method: 'GET',
			plane: 'regional',
			path: '/v1/folders',
			list: true,
			fields: [
				{ ...libraryLocator(), in: 'query' },
				{ ...folderLocator(), in: 'query', displayName: 'Parent Folder' },
				queryParam('recursive', 'Recursive', 'boolean', {
					description: 'Whether to include items in subfolders',
				}),
			],
		},
		{
			resource: 'folder',
			operation: 'get',
			name: 'Get',
			action: 'Get a folder',
			description: 'Retrieve one folder by ID',
			method: 'GET',
			plane: 'regional',
			path: '/v1/folders/{folderId}',
			params: [pathLocator('folderId', 'Folder', 'folder')],
		},
		{
			resource: 'folder',
			operation: 'create',
			name: 'Create',
			action: 'Create a folder',
			description: 'Create a folder at the library root or under a parent folder',
			method: 'POST',
			plane: 'regional',
			path: '/v1/folders',
			params: [bodyParam('name', 'Name', 'string', { required: true, placeholder: 'e.g. Campaign assets' })],
			fields: [
				{ ...libraryLocator(), description: 'Library that holds the item; Folder wins over Library when both are set' },
				{
					...folderLocator(),
					displayName: 'Parent Folder',
					description: 'Folder to create the new folder in; Folder wins over Library when both are set',
				},
			],
		},
		{
			resource: 'folder',
			operation: 'update',
			name: 'Update',
			action: 'Update a folder',
			description: 'Rename a folder or change its color',
			method: 'PATCH',
			plane: 'regional',
			path: '/v1/folders/{folderId}',
			params: [pathLocator('folderId', 'Folder', 'folder')],
			fields: [
				bodyParam('name', 'Name', 'string'),
				bodyParam('color', 'Color', 'string', { placeholder: 'e.g. #FF5A1F' }),
			],
		},
		{
			resource: 'folder',
			operation: 'move',
			name: 'Move',
			action: 'Move a folder',
			description: 'Move a folder to another library or parent folder',
			method: 'POST',
			plane: 'regional',
			path: '/v1/folders/{folderId}/move',
			params: [pathLocator('folderId', 'Folder', 'folder')],
			fields: [
				{ ...libraryLocator(), description: 'Library that holds the item; Folder wins over Library when both are set' },
				{
					...folderLocator(),
					displayName: 'Destination Folder',
					description: 'Folder to move the folder into; Folder wins over Library when both are set',
				},
			],
		},
		{
			resource: 'folder',
			operation: 'delete',
			name: 'Delete',
			action: 'Delete a folder',
			description: 'Move a folder to the trash, or delete it permanently',
			method: 'DELETE',
			plane: 'regional',
			path: '/v1/folders/{folderId}',
			params: [pathLocator('folderId', 'Folder', 'folder')],
			fields: [
				queryParam('permanent', 'Permanent', 'boolean', {
					description: 'Whether to delete permanently instead of moving to trash',
				}),
			],
			custom: deleteWithTrash,
		},
		{
			resource: 'folder',
			operation: 'restore',
			name: 'Restore',
			action: 'Restore a folder',
			description: 'Restore a folder that was moved to the trash',
			method: 'POST',
			plane: 'regional',
			path: '/v1/folders/{folderId}/restore',
			params: [pathLocator('folderId', 'Folder', 'folder')],
		},
	],
};
