import type { ResourceSpec } from '../catalogue/types';

export const library: ResourceSpec = {
	value: 'library',
	name: 'Library',
	description: 'Top-level containers of files and folders',
	operations: [
		{
			resource: 'library',
			operation: 'getAll',
			name: 'Get Many',
			action: 'Get many libraries',
			description: 'List the libraries the key can see',
			method: 'GET',
			plane: 'regional',
			path: '/v1/libraries',
			list: true,
		},
		{
			resource: 'library',
			operation: 'get',
			name: 'Get',
			action: 'Get a library',
			description: 'Retrieve one library with its counts',
			method: 'GET',
			plane: 'regional',
			path: '/v1/libraries/{libraryId}',
			params: [
				{
					displayName: 'Library',
					name: 'libraryId',
					in: 'path',
					type: 'string',
					required: true,
					default: '',
					locator: 'library',
				},
			],
		},
		{
			resource: 'library',
			operation: 'create',
			name: 'Create',
			action: 'Create a library',
			description: 'Create a new library',
			method: 'POST',
			plane: 'regional',
			path: '/v1/libraries',
			params: [
				{
					displayName: 'Name',
					name: 'name',
					in: 'body',
					type: 'string',
					required: true,
					default: '',
					placeholder: 'e.g. Brand assets',
				},
			],
			fields: [
				{ displayName: 'Description', name: 'description', in: 'body', type: 'string', default: '' },
				{ displayName: 'Emoji', name: 'emoji', in: 'body', type: 'string', default: '', placeholder: 'e.g. 📁' },
			],
		},
		{
			resource: 'library',
			operation: 'update',
			name: 'Update',
			action: 'Update a library',
			description: 'Rename a library or change its description',
			method: 'PATCH',
			plane: 'regional',
			path: '/v1/libraries/{libraryId}',
			params: [
				{
					displayName: 'Library',
					name: 'libraryId',
					in: 'path',
					type: 'string',
					required: true,
					default: '',
					locator: 'library',
				},
			],
			fields: [
				{ displayName: 'Name', name: 'name', in: 'body', type: 'string', default: '' },
				{ displayName: 'Description', name: 'description', in: 'body', type: 'string', default: '' },
			],
		},
		{
			resource: 'library',
			operation: 'delete',
			name: 'Delete',
			action: 'Delete a library',
			description: 'Delete a library and everything in it',
			method: 'DELETE',
			plane: 'regional',
			path: '/v1/libraries/{libraryId}',
			params: [
				{
					displayName: 'Library',
					name: 'libraryId',
					in: 'path',
					type: 'string',
					required: true,
					default: '',
					locator: 'library',
				},
			],
		},
	],
};
